---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nginx-2"
  namespace: "default"
  labels:
    app: "nginx-2"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "nginx-2"
  template:
    metadata:
      labels:
        app: "nginx-2"
    spec:
      containers:
      - name: "nginx-1"
        image: "CONTAINER_IMAGE"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "nginx-2-hpa-c5ut"
  namespace: "default"
  labels:
    app: "nginx-2"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "nginx-2"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "nginx-1-service"
  namespace: "default"
  labels:
    app: "nginx-1"
spec:
  ports:
  - protocol: "TCP"
    port: 80
  selector:
    app: "nginx-1"
  type: "LoadBalancer"
  loadBalancerIP: ""
