# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'deployment environment (dev or test or prod)'
        type: choice
        required: true
        options:
         - dev
         - test
         - prod

env:
  REGISTRY: gcr.io
  IMAGE_NAME: gke
  
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: trstringer/manual-approval@v1
      with:
       secret: ${{ secrets.TOKEN }}
       approvers: r4jeshwar
       minimum-approvals: 1
       issue-title: "Deploying v1.3.5 to prod from staging"
       issue-body: "Please approve or deny the deployment of version v1.3.5."
       exclude-workflow-initiator-as-approver: false
       additional-approved-words: 'yes'
       additional-denied-words: 'no'
       
    - name: Checkout
      uses: actions/checkout@v3
    
    #Install kubectl
    - name: Install Kubectl
      uses: azure/setup-kubectl@v3   
      with:
        version: 'v1.21.3' 
      id: install
    
    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0
      with:
        version: '270.0.0'
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        service_account_email: ${{ secrets.GCP_EMAIL }}
        project_id:  ${{ secrets.GCP_PROJECT_ID }}

    - name: Login GCR
      id: login_gcr
      uses: elgohr/gcloud-login-action@v1
      with:
        account_key: ${{ secrets.GCP_CREDENTIALS }}
    
    - name: Build and push to GCR
      uses: RafikFarhad/push-to-gcr-github-action@v5-beta
      with:
        gcloud_service_key: ${{ secrets.GCP_CREDENTIALS }}
        registry: ${{ env.REGISTRY }}
        project_id:  ${{ secrets.GCP_PROJECT_ID }}
        image_name: ${{ env.IMAGE_NAME }}
        image_tag: ${{ github.sha }}
        context: .
   
    - name: Update the docker image in the deployment file
      run: |
        sed -i 's@CONTAINER_IMAGE@'"${{ env.REGISTRY }}\/${{ secrets.GCP_PROJECT_ID }}\/${{ env.IMAGE_NAME }}:${{ github.sha }}"'@' deployment.yml
        cat deployment.yml
        
    # Deploy the application in GKE
    - name: Deploy the application
      uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBE_CONFIG }}
    - run: |
         kubectl get node    
         kubectl apply -f deployment.yml

    - name: Send mail
      if: always()
      uses: dawidd6/action-send-mail@v2
      with:
        # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
        # user credentials
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        # email subject
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
        # email body as text
        body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
        # comma-separated string, send email to
        to: eshwarraja2000@gmail.com
        # from email name
        from: GitHub Action
